mindmap
  root((Pembagian Rich Content Juli 2026))
      Penugasan
        Intent
        PIC
        Progress
        Status penugasan
          DONE
          DROP
      Template
        Accordion
        Chips
        Link
      Dian
        KUP_PKP_Pengukuhan Melalui Coretax
          Pembuka
          Payload
            Login Aplikasi Portal
            Menu Portal Saya
            Pengukuhan PKP/VAT Registration
            Status kepemilikan tempat usaha
            Data pendapatan tahunan
            Bulan mulai pemungutan PPN
            Alamat cabang di luar FTZ
            Pernyataan
      Topik dan menu bantuan
        Pelaporan SPT
        Perubahan Data
        Konfirmasi NPWP
        Aktivasi Akun Coretax
        Kode Otorisasi DJP
        Daftar NPWP
        Lupa EFIN
        Lupa EFIN Belum Aktivasi
        Lupa EFIN Sudah Aktivasi
        Mengaktifkan Kembali/Penonaktifan NPWP
        Cetak NPWP
        Kode Error Coretax
        PP Nomor 20 Tahun 2026
      Informasi layanan
        Jam layanan
          Senin s.d. Jumat
          08:00 - 16:00 WIB
        Kanal kontak
          Telepon 1500200
          Twitter @kring_pajak
          Email informasi@pajak.go.id
          Email pengaduan@pajak.go.id
        KPP terdekat
        Unit kerja
          https://pajak.go.id/unit-kerja
        Survei layanan
          https://s.kemenkeu.go.id/surveiDJPVA
      Ketentuan umum
        Jawaban VA bukan dasar hukum
        Simpan transkrip percakapan
      Lupa EFIN
        Status aktivasi EFIN
          Sudah aktivasi
          Belum aktivasi
        Cara memperoleh kembali EFIN
          M-Pajak
          Email lupa.efin@pajak.go.id
          Live Chat Kring Pajak
          Telepon Kring Pajak 1500200
          KPP/KP2KP
        Ketentuan permohonan
          Oleh Wajib Pajak sendiri
          Tidak dapat dikuasakan
        Aktivasi EFIN
          Hanya sekali
          Tidak melalui Kring Pajak
      Konfirmasi NPWP
        NIK sebagai NPWP
        Cek NPWP
          Coretax
          KPP terdekat
          Live chat 1500200
        Family Tax Unit
        Lembaga jasa keuangan
      Perubahan Data
        Jenis data
          KLU Utama
          Rekening Bank
        Langkah perubahan data
          Login Portal
          Menu Perubahan Data
          Identitas Wajib Pajak
          Unggah dokumen
          Submit/Kirim
          Unduh BPS
        Pemantauan kasus
          Portal Saya
          Kasus Saya
          Status Kasus
        Status permohonan
          Diproses
          Selesai
          Dibatalkan
          Ditarik
      Permintaan Kembali
        Email NPWP
        Aktivasi akun Coretax
        Unduh ulang dokumen
        Dokumen Saya
      Pendaftaran NPWP
        NPWP Orang Pribadi
        NPWP Badan
        NPWP Instansi Pemerintah
        Data tidak ditemukan
        Verify
        Kuasa pendaftaran badan
        KPP terdekat
        Pos/kurir
      Coretax
        Lupa kata sandi
        Aktivasi akun wajib pajak
        Email tidak dikonfigurasi
        Dokumen saya
        Unduh dokumen
        Generating document is in progress
      E-Faktur
        E-Faktur Desktop
        E-Faktur Web
        Password e-Nofa
      Sertifikat digital dan kode otorisasi
        Permohonan Kode Otorisasi/Sertifikat Digital
        Lupa passphrase
        Kode otorisasi DJP
      Pengaduan
        Pengaduan umum
        Layanan Pengaduan, Saran, dan Apresiasi
        Dit. P2Humas
      Penetapan Wajib Pajak Kriteria Tertentu
        Pengembalian pendahuluan
        PMK 28 Tahun 2026
        Pengajuan kembali